import {
	Component,
	ChangeDetectionStrategy,
	ElementRef,
	OnDestroy,
	TemplateRef,
	computed,
	contentChildren,
	input,
	inject,
	signal,
	effect,
	viewChild,
	TrackByFunction,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import {
	InteropCollectionInput,
	isCollection,
} from "../../../types/collection";
import { InteropCollectionService } from "../../services/interop-collection.service";
import {
	InteropAttribute,
	SetAttrsConfig,
	PresetKey,
} from "../../services/interop-attribute.service";
import { createComponentTrackByFn } from "../../utils/track-by";
import { InteropCellDef, InteropCellContext } from "./interop-cell-def";

/**
 * Column definition for InteropTable.
 */
export interface TableColumn<T = any> {
	/** Property key from the data object to display. */
	key: keyof T | string;

	/** Display label for the column header. Defaults to the key name. */
	label?: string;

	/** Whether this column is hidden. */
	hidden?: boolean;

	/**
	 * Whether this column sticks to the left edge during horizontal scroll.
	 * Apply to the leftmost column(s) only.
	 */
	sticky?: boolean;

	/**
	 * Explicit left offset in pixels for sticky columns.
	 * Required only when multiple consecutive columns are sticky.
	 * The first sticky column is always `left: 0`; subsequent sticky columns
	 * must declare their offset manually (sum of all preceding sticky column widths).
	 */
	stickyLeft?: number;
}

/**
 * InteropTable — Semantic, signal-based table component.
 *
 * @example Basic
 * ```html
 * <interop-table [collection]="users" />
 * ```
 *
 * @example Scrollable with sticky first column
 * ```html
 * <interop-table
 *   [collection]="rows"
 *   [columns]="cols"
 *   [scrollable]="true"
 *   scrollLabel="Cargo manifest"
 * />
 * ```
 * Where `cols[0]` has `sticky: true`.
 */
@Component({
	selector: "interop-table",
	standalone: true,
	imports: [CommonModule],
	templateUrl: "./interop-table.html",
	styleUrl: "./interop-table.scss",
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class InteropTable<T = any> implements OnDestroy {
	private readonly collectionService = inject(InteropCollectionService);
	private readonly attrsManager = inject(InteropAttribute);
	private readonly scrollContainerEl =
		viewChild<ElementRef<HTMLDivElement>>("scrollContainerEl");

	// ── Inputs ────────────────────────────────────────────────────────────────

	/** Data collection. Accepts arrays, Observables, Promises, or InteropCollection. */
	collection = input<InteropCollectionInput<T>>();

	/** Column definitions. Auto-generated from first data item when omitted. */
	columns = input<TableColumn<T>[] | null>(null);

	/** Row tracking strategy: 'auto', 'index', or a custom TrackByFunction. */
	trackBy = input<TrackByFunction<T> | "auto" | "index">("auto");

	/** Field to use for identity tracking when trackBy is 'auto'. */
	trackByField = input<keyof T | null>(null);

	/** Whether to show column header row. */
	showHeaders = input<boolean>(true);

	/** Text shown when no data is available. */
	emptyText = input<string>("No data available");

	/** Text shown while loading. */
	loadingText = input<string>("Loading...");

	/** Auto-generate columns from the first data item when no columns are provided. */
	autoColumns = input<boolean>(true);

	/** Maximum number of rows to display. null = no limit. */
	maxRows = input<number | null>(null);

	/**
	 * Enable horizontal overflow scrolling.
	 * The table is wrapped in a focusable scroll region with role="region" and
	 * an accessible label. Combine with `sticky: true` on key columns.
	 */
	scrollable = input<boolean>(false);

	/**
	 * Accessible label for the scroll region.
	 * Announced by screen readers as "Label, region".
	 * Defaults to "Scrollable table" when not provided.
	 */
	scrollLabel = input<string | null>(null);

	// ── Content children ──────────────────────────────────────────────────────

	private readonly cellDefs = contentChildren(InteropCellDef);

	readonly cellTemplateMap = computed(() => {
		const map = new Map<string, TemplateRef<InteropCellContext<T>>>();
		for (const def of this.cellDefs()) {
			map.set(def.itxCell(), def.templateRef);
		}
		return map;
	});

	// ── Internal state ────────────────────────────────────────────────────────

	private readonly collectionInstance = signal<any>(null);
	private readonly autoGeneratedColumns = signal<TableColumn<T>[]>([]);
	private rafId: number | null = null;

	/** True once the scroll container has been scrolled past its left origin. */
	readonly isScrolled = signal(false);

	// ── Computed ──────────────────────────────────────────────────────────────

	readonly resolvedCollection = computed(() => {
		const collection = this.collection();
		if (!collection) return null;
		const existing = this.collectionService.computedResolve(collection);
		if (existing) return existing;
		return this.collectionInstance();
	});

	readonly items = computed(() => {
		const items = this.resolvedCollection()?.items() ?? [];
		const max = this.maxRows();
		return max == null ? items : items.slice(0, max);
	});

	readonly isLoading = computed(() => this.resolvedCollection()?.loading() ?? false);
	readonly hasError = computed(() => this.resolvedCollection()?.hasError() ?? false);
	readonly isEmpty = computed(() => this.resolvedCollection()?.isEmpty() ?? true);

	readonly resolvedColumns = computed(() => {
		const custom = this.columns();
		if (custom && custom.length > 0) return custom.filter((c) => !c.hidden);
		if (this.autoColumns()) return this.autoGeneratedColumns().filter((c) => !c.hidden);
		return [];
	});

	readonly hasStickyColumns = computed(() =>
		this.resolvedColumns().some((c) => c.sticky),
	);

	// ── Lifecycle ─────────────────────────────────────────────────────────────

	constructor() {
		effect(() => {
			const collectionInput = this.collection();
			if (collectionInput) {
				this.collectionInstance.set(
					this.collectionService.resolve(collectionInput),
				);
			} else {
				this.collectionInstance.set(null);
			}
		});

		effect(() => {
			const items = this.items();
			const custom = this.columns();
			if (
				this.autoColumns() &&
				(!custom || custom.length === 0) &&
				items.length > 0
			) {
				this.autoGeneratedColumns.set(this.generateColumnsFromData(items[0]));
			} else if (!this.autoColumns() || (custom && custom.length > 0)) {
				this.autoGeneratedColumns.set([]);
			}
		});
	}

	ngOnDestroy(): void {
		if (this.rafId !== null) {
			cancelAnimationFrame(this.rafId);
			this.rafId = null;
		}
	}

	// ── Scroll handling ───────────────────────────────────────────────────────

	onScroll(): void {
		if (this.rafId !== null) return;
		this.rafId = requestAnimationFrame(() => {
			this.rafId = null;
			const el = this.scrollContainerEl()?.nativeElement;
			this.isScrolled.set((el?.scrollLeft ?? 0) > 1);
		});
	}

	// ── Template helpers ──────────────────────────────────────────────────────

	getCellTemplate(column: TableColumn<T>): TemplateRef<InteropCellContext<T>> | null {
		return this.cellTemplateMap().get(String(column.key)) ?? null;
	}

	getCellText(item: T, column: TableColumn<T>): string {
		const value = (item as any)?.[column.key as string];
		if (value == null) return "";
		return String(value);
	}

	getColumnLabel(column: TableColumn<T>): string {
		return column.label ?? String(column.key);
	}

	getStickyLeft(column: TableColumn<T>): string {
		return `${column.stickyLeft ?? 0}px`;
	}

	trackByFn = createComponentTrackByFn<T>(
		() => this.trackBy(),
		() => this.trackByField(),
	);

	trackByColumnIndex = (_index: number, column: TableColumn<T>): any => column.key;

	// ── Private ───────────────────────────────────────────────────────────────

	private generateColumnsFromData(firstItem: T): TableColumn<T>[] {
		if (!firstItem || typeof firstItem !== "object") return [];
		return (Object.keys(firstItem) as (keyof T)[]).map((key) => ({
			key,
			label: this.formatKeyAsLabel(String(key)),
		}));
	}

	private formatKeyAsLabel(key: string): string {
		return key
			.replace(/([a-z])([A-Z])/g, "$1 $2")
			.replace(/[_-]/g, " ")
			.toLowerCase()
			.replace(/^\w/, (c) => c.toUpperCase());
	}
}
