import {
	ChangeDetectionStrategy,
	Component,
	DestroyRef,
	ElementRef,
	afterNextRender,
	computed,
	effect,
	inject,
	input,
	isDevMode,
	model,
	output,
} from "@angular/core";
import { InteropSliderRegistry } from "./interop-slider-registry";
import {
	INTEROP_SLIDER_TOKEN,
	type InteropSliderApi,
	type SliderOrientation,
	type SliderValueFormatter,
} from "./interop-slider.token";

let idCounter = 0;
export function generateSliderId(): string {
	return `itx-slider-${++idCounter}`;
}

/**
 * InteropSlider — semantic single-thumb slider built on the native
 * `<input type="range">` element.
 *
 * Apply to any `<input type="range">`. The directive owns ARIA wiring,
 * fill-percentage CSS variable, optional `aria-valuetext` formatting, and
 * dev-mode validation. Keyboard, drag, touch, RTL, and form participation
 * are all handled by the browser — the directive does not re-implement them.
 *
 * Min / max / step / value are declared as signal inputs and drive both
 * the native attributes and the directive's reactive state. Use property
 * binding syntax (`[min]`, `[max]`, `[step]`, `[(value)]`) so the signals
 * stay in sync with the rendered attributes.
 *
 * Form participation is automatic — the host is a real `<input>` and submits
 * with its surrounding `<form>` like any other input.
 *
 * @example Basic horizontal slider with two-way value binding
 * ```html
 * <label for="brightness">Brightness</label>
 * <input type="range" interop-slider id="brightness"
 *        [min]="0" [max]="100" [step]="1" [(value)]="brightness"
 *        name="brightness" />
 * ```
 *
 * @example With value display companion
 * ```html
 * <label for="vol">Volume</label>
 * <input type="range" interop-slider id="vol"
 *        [min]="0" [max]="100" [(value)]="vol" />
 * <output interop-slider-value for="vol"></output>
 * ```
 *
 * @example Non-numeric `aria-valuetext`
 * ```html
 * <label for="size">Shirt size</label>
 * <input type="range" interop-slider id="size"
 *        [min]="0" [max]="3" [step]="1" [(value)]="size"
 *        [valueText]="(v) => SIZES[v]" />
 * ```
 *
 * @example Vertical orientation
 * ```html
 * <input type="range" interop-slider
 *        [orientation]="'vertical'"
 *        [(value)]="temperature"
 *        aria-label="Temperature" />
 * ```
 */
@Component({
	selector: "input[type=range][interop-slider]",
	standalone: true,
	template: "",
	styleUrl: "./interop-slider.css",
	changeDetection: ChangeDetectionStrategy.OnPush,
	providers: [
		{ provide: INTEROP_SLIDER_TOKEN, useExisting: InteropSlider },
	],
	host: {
		"[disabled]": "disabled()",
		"[attr.name]": "name()",
		"[attr.aria-valuetext]": "computedValueText()",
		"[attr.aria-orientation]":
			"orientation() === 'vertical' ? 'vertical' : null",
		"[attr.data-orientation]": "orientation()",
		"[style.--itx-slider-fill]": "fillPercent() + '%'",
		"(input)": "onInput($event)",
		"(change)": "onChange($event)",
	},
})
export class InteropSlider implements InteropSliderApi {
	private readonly elementRef = inject(ElementRef<HTMLInputElement>);
	private readonly registry = inject(InteropSliderRegistry);
	private readonly destroyRef = inject(DestroyRef);

	/** Minimum value. Defaults to 0. */
	readonly min = input<number>(0);

	/** Maximum value. Defaults to 100. */
	readonly max = input<number>(100);

	/** Step granularity. Defaults to 1. */
	readonly step = input<number>(1);

	/**
	 * Current value. Two-way bindable as `[(value)]`. Updated automatically
	 * when the user drags or keys; the new value is emitted via
	 * `valueChange` (auto-generated by `model()`).
	 *
	 * Note: when used together with `ngModel` / `formControl`, the
	 * Reactive Forms binding owns the native `value` and this model
	 * may not stay in sync. Pick one binding strategy per slider.
	 */
	readonly value = model<number>(0);

	/** Disable the slider. Native disabled — prevents focus and interaction. */
	readonly disabled = input<boolean>(false);

	/** Optional form-submission name. */
	readonly name = input<string | null>(null);

	/** Layout orientation. Vertical uses `writing-mode: vertical-lr`. */
	readonly orientation = input<SliderOrientation>("horizontal");

	/**
	 * Optional formatter that drives `aria-valuetext`. Set ONLY when the raw
	 * numeric value would mislead a screen-reader user (e.g., the slider
	 * represents discrete categories like "Low / Medium / High", or the
	 * displayed value differs in scale from `value()`).
	 *
	 * For purely cosmetic visual formatting (e.g., `$1,200`), leave this
	 * unset and provide `[format]` on the `<output interop-slider-value>`
	 * companion instead — that way the screen reader continues to announce
	 * the raw number, which speech engines pronounce more reliably than
	 * a currency-symbol-prefixed string.
	 */
	readonly valueText = input<SliderValueFormatter | null>(null);

	/**
	 * Emitted on the `change` event — i.e., when the user releases the
	 * thumb after a drag, or commits a keyboard adjustment. Use for
	 * "value committed" semantics (saving, network calls). For continuous
	 * updates during drag, listen to `valueChange` instead.
	 */
	readonly interactionEnd = output<number>();

	readonly fillPercent = computed(() => {
		const min = this.min();
		const max = this.max();
		const v = this.value();
		if (max === min) return 0;
		return Math.max(0, Math.min(100, ((v - min) / (max - min)) * 100));
	});

	readonly computedValueText = computed(() => {
		const fn = this.valueText();
		return fn ? fn(this.value()) : null;
	});

	get element(): HTMLInputElement {
		return this.elementRef.nativeElement;
	}

	elementId(): string {
		const el = this.elementRef.nativeElement;
		if (!el.id) el.id = generateSliderId();
		return el.id;
	}

	constructor() {
		// Sync min/max/step BEFORE value — the native input clamps `.value` to
		// the current `[min, max]` at the moment of assignment, so a value
		// outside the default range gets silently clipped if applied first.
		effect(() => {
			const el = this.elementRef.nativeElement;
			el.min = String(this.min());
			el.max = String(this.max());
			el.step = String(this.step());
			el.value = String(this.value());
		});

		afterNextRender(() => {
			const id = this.elementId();
			this.registry.register(this);
			this.destroyRef.onDestroy(() => this.registry.unregister(id));

			if (isDevMode()) this.devModeChecks();
		});
	}

	protected onInput(event: Event): void {
		const v = parseFloat((event.target as HTMLInputElement).value);
		if (!Number.isNaN(v)) this.value.set(v);
	}

	protected onChange(event: Event): void {
		const v = parseFloat((event.target as HTMLInputElement).value);
		if (!Number.isNaN(v)) this.interactionEnd.emit(v);
	}

	private devModeChecks(): void {
		const el = this.elementRef.nativeElement;

		if (el.tagName !== "INPUT" || el.type !== "range") {
			console.warn(
				"[InteropSlider] Must be applied to <input type=\"range\">. " +
					`Found <${el.tagName.toLowerCase()} type="${el.type}">.`,
			);
			return;
		}

		const hasAriaLabel = el.hasAttribute("aria-label");
		const hasAriaLabelledBy = el.hasAttribute("aria-labelledby");
		const hasNativeLabel = el.id
			? !!document.querySelector(`label[for="${el.id}"]`)
			: false;
		const wrappedByLabel = !!el.closest("label");

		if (!hasAriaLabel && !hasAriaLabelledBy && !hasNativeLabel && !wrappedByLabel) {
			console.warn(
				"[InteropSlider] No accessible name found. Add a <label for>, " +
					"aria-label, or aria-labelledby.",
			);
		}

		const min = this.min();
		const max = this.max();
		const step = this.step();
		const v = this.value();

		if (min >= max) {
			console.warn(
				`[InteropSlider] min (${min}) must be less than max (${max}).`,
			);
		}
		if (step <= 0) {
			console.warn(
				`[InteropSlider] step (${step}) must be a positive number.`,
			);
		}
		if (v < min || v > max) {
			console.warn(
				`[InteropSlider] value (${v}) is outside [${min}, ${max}].`,
			);
		}

		// Floating-point hazard — warn when (max - min) / step does not divide cleanly.
		if (step > 0 && max > min) {
			const stepsCount = (max - min) / step;
			if (Math.abs(stepsCount - Math.round(stepsCount)) > 1e-9) {
				console.warn(
					`[InteropSlider] (max - min) / step = ${stepsCount} is not an ` +
						"integer. Floating-point drift will cause displayed values to " +
						"diverge from clean step boundaries.",
				);
			}
		}
	}
}
