// AUTO-GENERATED from .djot source. Do not edit by hand.
import type { Div } from '@djot/djot';

export const hero: Div = /*#__PURE__*/ Object.freeze({"tag":"div","children":[{"tag":"heading","level":1,"children":[{"tag":"str","text":"Authoring with djot"}],"autoAttributes":{"id":"Authoring-with-djot"}},{"tag":"para","children":[{"tag":"str","text":"A "},{"tag":"strong","children":[{"tag":"str","text":"single"}]},{"tag":"str","text":" source file, "},{"tag":"strong","children":[{"tag":"strong","children":[{"tag":"str","text":"many"}]}]},{"tag":"str","text":" mount points. Each top-level "},{"tag":"verbatim","text":":::"},{"tag":"str","text":"-block with"},{"tag":"soft_break"},{"tag":"str","text":"an "},{"tag":"verbatim","text":"{#id}"},{"tag":"str","text":" becomes a typed export — projected into the DOM wherever the page"},{"tag":"soft_break"},{"tag":"str","text":"needs it."}]}],"attributes":{"id":"hero","class":"lead"}}) as unknown as Div;
export const install: Div = /*#__PURE__*/ Object.freeze({"tag":"div","children":[{"tag":"code_block","text":"npm install @djot/djot\n","lang":"bash"}],"attributes":{"id":"install"}}) as unknown as Div;
export const features: Div = /*#__PURE__*/ Object.freeze({"tag":"div","children":[{"tag":"bullet_list","tight":true,"style":"-","children":[{"tag":"list_item","children":[{"tag":"para","children":[{"tag":"str","text":"Predictable parser — block structure resolves before inlines"}]}]},{"tag":"list_item","children":[{"tag":"para","children":[{"tag":"str","text":"Native block attributes — "},{"tag":"verbatim","text":"{#id .class key=value}"},{"tag":"str","text":" on any block"}]}]},{"tag":"list_item","children":[{"tag":"para","children":[{"tag":"str","text":"Generic divs and spans — no plugins required"}]}]},{"tag":"list_item","children":[{"tag":"para","children":[{"tag":"str","text":"Symbol syntax for renderer hooks — "},{"tag":"verbatim","text":":icon-name:"}]}]}]}],"attributes":{"id":"features"}}) as unknown as Div;
export const tradeoffs: Div = /*#__PURE__*/ Object.freeze({"tag":"div","children":[{"tag":"table","children":[{"tag":"caption","children":[]},{"tag":"row","children":[{"tag":"cell","children":[{"tag":"str","text":"Concern"}],"head":true,"align":"right"},{"tag":"cell","children":[{"tag":"str","text":"djot"}],"head":true,"align":"left"},{"tag":"cell","children":[{"tag":"str","text":"markdown"}],"head":true,"align":"left"}],"head":true},{"tag":"row","children":[{"tag":"cell","children":[{"tag":"str","text":"Named regions"}],"head":false,"align":"right"},{"tag":"cell","children":[{"tag":"str","text":"first"},{"tag":"str","text":"-"},{"tag":"str","text":"class"}],"head":false,"align":"left"},{"tag":"cell","children":[{"tag":"str","text":"extension required"}],"head":false,"align":"left"}],"head":false},{"tag":"row","children":[{"tag":"cell","children":[{"tag":"str","text":"Parser ambiguity"}],"head":false,"align":"right"},{"tag":"cell","children":[{"tag":"str","text":"none"}],"head":false,"align":"left"},{"tag":"cell","children":[{"tag":"str","text":"many edge cases"}],"head":false,"align":"left"}],"head":false},{"tag":"row","children":[{"tag":"cell","children":[{"tag":"str","text":"Ecosystem maturity"}],"head":false,"align":"right"},{"tag":"cell","children":[{"tag":"str","text":"small"}],"head":false,"align":"left"},{"tag":"cell","children":[{"tag":"str","text":"huge"}],"head":false,"align":"left"}],"head":false},{"tag":"row","children":[{"tag":"cell","children":[{"tag":"str","text":"Editor familiarity"}],"head":false,"align":"right"},{"tag":"cell","children":[{"tag":"str","text":"low"}],"head":false,"align":"left"},{"tag":"cell","children":[{"tag":"str","text":"high"}],"head":false,"align":"left"}],"head":false}]}],"attributes":{"id":"tradeoffs"}}) as unknown as Div;
export const footer: Div = /*#__PURE__*/ Object.freeze({"tag":"div","children":[{"tag":"block_quote","children":[{"tag":"para","children":[{"tag":"str","text":"djot is by John MacFarlane, who also designed CommonMark and pandoc."}]}]}],"attributes":{"id":"footer"}}) as unknown as Div;

export const __slots = ["hero", "install", "features", "tradeoffs", "footer"] as const;
export type Slot = typeof __slots[number];
