// AUTO-GENERATED from .djot source. Do not edit by hand.
import type { Div } from '@djot/djot';

export const overview: Div = /*#__PURE__*/ Object.freeze({"tag":"div","children":[{"tag":"para","children":[{"tag":"str","text":"InteropButton styles are driven purely by Interop"},{"tag":"str","text":"'s bundled CSS."},{"tag":"soft_break"},{"tag":"str","text":"Use our prerolls (and roll your own) with no imports (not even InteropButton) and no associated bundle cost."}]}],"attributes":{"id":"overview"}}) as unknown as Div;
export const sizes: Div = /*#__PURE__*/ Object.freeze({"tag":"div","children":[{"tag":"para","children":[{"tag":"str","text":"Interop ships five button sizes: "},{"tag":"verbatim","text":"xs"},{"tag":"str","text":", "},{"tag":"verbatim","text":"sm"},{"tag":"str","text":", "},{"tag":"verbatim","text":"md"},{"tag":"str","text":", "},{"tag":"verbatim","text":"lg"},{"tag":"str","text":", "},{"tag":"verbatim","text":"xl"},{"tag":"str","text":"."}]},{"tag":"para","children":[{"tag":"str","text":"Why would you want an extra-small and an extra-large button? I don"},{"tag":"smart_punctuation","type":"right_single_quote","text":"'"},{"tag":"str","text":"t know. I"},{"tag":"smart_punctuation","type":"right_single_quote","text":"'"},{"tag":"str","text":"m not a good guesser."},{"tag":"soft_break"},{"tag":"str","text":"The extra small button only provides a vertical click height of ~25px."},{"tag":"soft_break"},{"tag":"str","text":"Even assuming a fine pointer context, that"},{"tag":"smart_punctuation","type":"right_single_quote","text":"'"},{"tag":"str","text":"s too small for anyone"},{"tag":"smart_punctuation","type":"right_single_quote","text":"'"},{"tag":"str","text":"s comfort. I"},{"tag":"smart_punctuation","type":"right_single_quote","text":"'"},{"tag":"str","text":"d skip it entirely."}]},{"tag":"para","children":[{"tag":"str","text":"(default, "},{"tag":"strong","children":[{"tag":"str","text":"action-minus"}]},{"tag":"str","text":", "},{"tag":"strong","children":[{"tag":"str","text":"action"}]},{"tag":"str","text":", "},{"tag":"strong","children":[{"tag":"str","text":"action-plus"}]},{"tag":"str","text":") plus a "},{"tag":"strong","children":[{"tag":"str","text":"colorway"}]},{"tag":"str","text":" variant."},{"tag":"soft_break"},{"tag":"str","text":"Drop the size onto "},{"tag":"verbatim","text":"interop-button=\"<size>\""},{"tag":"str","text":" and the variant onto"},{"tag":"soft_break"},{"tag":"verbatim","text":"interop-button=\"<variant> <size>\""},{"tag":"str","text":"."},{"tag":"soft_break"},{"tag":"str","text":"Interop provides a straightforward token system for creating buttons that feel right at home in your design. The default button styles shown here can be used as is or as models for your own exploration."},{"tag":"soft_break"},{"tag":"str","text":"Every Interop button is built atop the same chassis."},{"tag":"soft_break"},{"tag":"str","text":"This means that any button can be transformed into any other Interop button simply by changing the string values in the "},{"tag":"verbatim","text":"interop-button"},{"tag":"str","text":"  attribute."}]}],"attributes":{"id":"sizes"}}) as unknown as Div;
export const disabled: Div = /*#__PURE__*/ Object.freeze({"tag":"div","children":[{"tag":"para","children":[{"tag":"str","text":"Setting "},{"tag":"verbatim","text":"[disabled]=\"true\""},{"tag":"str","text":" blocks pointer and keyboard activation, applies"},{"tag":"soft_break"},{"tag":"str","text":"the standard disabled styling, and ensures assistive tech announces the"},{"tag":"soft_break"},{"tag":"str","text":"button as unavailable. No additional ARIA wiring needed."}]}],"attributes":{"id":"disabled"}}) as unknown as Div;
export const loading: Div = /*#__PURE__*/ Object.freeze({"tag":"div","children":[{"tag":"para","children":[{"tag":"verbatim","text":"[loading]=\"true\""},{"tag":"str","text":" swaps the label for an indeterminate spinner and prevents"},{"tag":"soft_break"},{"tag":"str","text":"activation while in flight. The button keeps its width so surrounding layout"},{"tag":"soft_break"},{"tag":"str","text":"doesn"},{"tag":"smart_punctuation","type":"right_single_quote","text":"'"},{"tag":"str","text":"t shift when the state toggles."}]}],"attributes":{"id":"loading"}}) as unknown as Div;
export const throttle: Div = /*#__PURE__*/ Object.freeze({"tag":"div","children":[{"tag":"para","children":[{"tag":"str","text":"The handler fires "},{"tag":"strong","children":[{"tag":"str","text":"immediately"}]},{"tag":"str","text":" on the leading edge, then ignores further"},{"tag":"soft_break"},{"tag":"str","text":"activations for the configured window. Use this when the action represents a"},{"tag":"soft_break"},{"tag":"str","text":"discrete burst — a click that should never be missed, but also never doubled."}]}],"attributes":{"id":"throttle"}}) as unknown as Div;
export const debounce: Div = /*#__PURE__*/ Object.freeze({"tag":"div","children":[{"tag":"para","children":[{"tag":"str","text":"Activation is "},{"tag":"strong","children":[{"tag":"str","text":"deferred"}]},{"tag":"str","text":" until the user stops clicking. Each new click resets"},{"tag":"soft_break"},{"tag":"str","text":"the timer. Best for search-as-you-type or any handler whose work is wasted if"},{"tag":"soft_break"},{"tag":"str","text":"another click is on its way."}]}],"attributes":{"id":"debounce"}}) as unknown as Div;
export const reentrancy: Div = /*#__PURE__*/ Object.freeze({"tag":"div","children":[{"tag":"para","children":[{"tag":"str","text":"With "},{"tag":"verbatim","text":"reentrant: false"},{"tag":"str","text":", a second click while the handler is still running is"},{"tag":"soft_break"},{"tag":"str","text":"silently dropped. Pair this with async handlers (network, file IO) where a"},{"tag":"soft_break"},{"tag":"str","text":"double-submit would be a correctness bug, not just a UX annoyance."}]}],"attributes":{"id":"reentrancy"}}) as unknown as Div;
export const playground: Div = /*#__PURE__*/ Object.freeze({"tag":"div","children":[{"tag":"para","children":[{"tag":"str","text":"With "},{"tag":"verbatim","text":"reentrant: false"},{"tag":"str","text":", a second click while the handler is still running is"},{"tag":"soft_break"},{"tag":"str","text":"silently dropped. Pair this with async handlers (network, file IO) where a"},{"tag":"soft_break"},{"tag":"str","text":"double-submit would be a correctness bug, not just a UX annoyance."}]}],"attributes":{"id":"playground"}}) as unknown as Div;

export const __slots = ["overview", "sizes", "disabled", "loading", "throttle", "debounce", "reentrancy", "playground"] as const;
export type Slot = typeof __slots[number];
