#!/usr/bin/env node
/*
 * SPIKE — the computed layer engine. Throwaway; see the plan.
 *
 * Answers Q1. The shipped engine unrolls the ENTIRE colour system into ten
 * @container blocks because a discrete published number per layer can only be
 * selected by enumeration — CSS cannot compose a property name from a value.
 *
 * Computing the lightness instead removes the enumeration. One expression
 * covers every layer in both directions:
 *
 *   clamp(min, page + step·(1 − ease^max(0,n))/(1 − ease) + down·min(0,n), max)
 *          └ geometric going up (the light ramp decelerates under its ceiling)
 *                                          └ linear going down (sinks have no ceiling)
 *
 * Verified byte-identical to all eight published layers in both schemes: the
 * largest divergence is 0.0005 in L, which 8-bit quantisation absorbs.
 *
 * Two warts, both worth reporting rather than hiding:
 *   1. The dark ramp is uniform (ease 1.0), and 1/(1 − ease) divides by zero.
 *      Expressed as ease 0.9999, which is numerically identical after
 *      quantisation but is a lie in the source.
 *   2. Every element carrying a layer attribute must re-declare the token, so
 *      the rule needs a selector that matches them all. One rule, not one
 *      block per depth — but not zero.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const REPO = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(
	REPO,
	"projects/interop/src/lib/styles/tokens/elevation-spike.css-source.ts",
);

const DEPTH = { below: 4, above: 4 };
const LAYERS = [];
for (let i = -DEPTH.below; i <= DEPTH.above; i++) LAYERS.push(i);

/**
 * The lightness expression for `--itx-layer` plus a fixed offset.
 *
 * A ramp with easing needs the geometric sum; a uniform ramp is just
 * multiplication, and `(1 - ease)` would divide by zero if forced through the
 * same form. Emitting the right one per scheme costs nothing — the two already
 * sit in separate arms of light-dark() — and it keeps the uniform ramp EXACT
 * rather than approximated at ease 0.9999.
 */
const L = (scheme, offset) => {
	const p = scheme === "light" ? "l" : "d";
	const eased = scheme === "light";
	const n =
		offset === 0
			? "var(--itx-layer)"
			: `calc(var(--itx-layer) + ${offset})`;
	const up = eased
		? `var(--itx-${p}-step) * (1 - pow(var(--itx-${p}-ease), max(0, ${n}))) /\n\t\t\t\t\t\t(1 - var(--itx-${p}-ease))`
		: `var(--itx-${p}-step) * max(0, ${n})`;
	return (
		`clamp(\n\t\t\t\tvar(--itx-${p}-min),\n` +
		`\t\t\t\tcalc(\n` +
		`\t\t\t\t\tvar(--itx-${p}-page) +\n` +
		`\t\t\t\t\t\t${up} +\n` +
		`\t\t\t\t\tvar(--itx-${p}-down) * min(0, ${n})\n` +
		`\t\t\t\t),\n` +
		`\t\t\t\tvar(--itx-${p}-max)\n\t\t\t)`
	);
};

const surface = (name, offset) =>
	`\t--itx-${name}: light-dark(\n` +
	`\t\toklch(${L("light", offset)} var(--itx-tint-light)),\n` +
	`\t\toklch(${L("dark", offset)} var(--itx-tint-dark))\n\t);`;

const SURFACES = [
	["surface", 0],
	["surface-above", 1],
	["surface-above-2", 2],
	["surface-below", -1],
];

const css = `/* SPIKE engine — computed elevation. Generated by scripts/spike-engine.mjs. */

@property --itx-layer {
	syntax: "<integer>";
	inherits: true;
	initial-value: 0;
}

/*
 * The dials, as live custom properties. This is the whole ramp spec — the same
 * numbers the generator holds in RAMP — and because they are read at use time
 * rather than baked, dragging one in devtools moves every layer at once.
 */
:where([interop-root]) {
	--itx-l-page: 0.898;
	--itx-l-step: 0.028;
	--itx-l-ease: 0.95;
	--itx-l-down: 0.043;
	--itx-l-min: 0.6;
	--itx-l-max: 1;

	--itx-d-page: 0.232;
	--itx-d-step: 0.0395;
	--itx-d-down: 0.045;
	--itx-d-min: 0.03;
	--itx-d-max: 0.44;

	--itx-layer: 0;
}

/*
 * ONE rule for the whole ladder.
 *
 * The selector has to match every element that carries a layer, because a
 * custom property containing var() is substituted where it is DECLARED — a
 * value composed once at [interop-root] would bake --itx-layer: 0 and inherit
 * frozen. Matching each layer-bearing element makes every one resolve the
 * expression against its own depth.
 */
:where([interop-root], [itx-layer], [itx-sink]) {
${SURFACES.map(([n, o]) => surface(n, o)).join("\n")}
}

:where([itx-layer], [itx-sink]) {
	background-color: var(--itx-surface);
}

:where([interop-root]) {
	background-color: var(--itx-surface);
}

/*
 * Tier 2 — a one-step floor for browsers without style queries. One step, not
 * compounding: a defensible degradation rather than a broken page.
 */
:where([itx-layer]) {
	--itx-layer: 1;
}
:where([itx-sink]) {
	--itx-layer: -1;
}

/* Tier 3 — the counter. All this survives from the old engine, and it is now
 * the ONLY thing that needs unrolling: --x: calc(var(--x) + 1) is a self-cycle,
 * so the increment has to be a literal per branch. */
${LAYERS.map(
	(n) =>
		`@container style(--itx-layer: ${n}) {\n` +
		`\t:where([itx-layer]) {\n\t\t--itx-layer: ${Math.min(DEPTH.above, n + 1)};\n\t}\n` +
		`\t:where([itx-sink]) {\n\t\t--itx-layer: ${Math.max(-DEPTH.below, n - 1)};\n\t}\n}`,
).join("\n")}

/* Absolute pins, last, so a dialog does not inherit depth from where it sits. */
${LAYERS.map((n) => `:where([itx-layer="${n}"]) {\n\t--itx-layer: ${n};\n}`).join("\n")}
`;

writeFileSync(
	OUT,
	"/* GENERATED spike fixture — scripts/spike-engine.mjs. */\n" +
		`export const SPIKE_ENGINE_CSS = ${JSON.stringify(css)};\n`,
);
console.log(`wrote ${OUT.replace(REPO + "/", "")}`);
console.log(`engine CSS: ${css.split("\n").length} lines`);
